import {
  BankOutlined,
  WalletOutlined,
  RobotOutlined,
  BuildOutlined,
  TrophyOutlined,
  TeamOutlined,
  StarOutlined,
  SettingOutlined,
  DashboardOutlined,
  CalendarOutlined,
  HistoryOutlined,
  BarChartOutlined,
  LineChartOutlined,
  DatabaseOutlined,
} from "@ant-design/icons";
import BASE_URL from "../../../core/config/Config";

/* ── Sidebar nav ─────────────────────────────────────────── */
export const NAV_SECTIONS = [
  {
    label: "USERS REGISTRATIONS",
    items: [
      { icon: "dashboard", label: "Dashboard", key: "dashboard" },
      { icon: "lender", label: "OxyLoans Lender", key: "lender" },
      { icon: "borrower", label: "OxyLoans Borrower", key: "borrower" },
      { icon: "askoxy", label: "AskOxy.AI", key: "askoxy" },
      { icon: "oxybricks", label: "OxyBricks", key: "oxybricks" },
      { icon: "oxygold", label: "OxyGold", key: "oxygold" },
      { icon: "partnerlender", label: "Oxyloans Partner", key: "partnerlender" },
      { icon: "interested", label: "Interested", key: "interested" },
    ],
  },
  {
    label: "Queries",
    items: [
      { icon: "dashboard", label: "Dashboard", key: "queriesDashboard" },
      { icon: "askoxy", label: "AskOxy.AI", key: "queriesAskoxy" },
      { icon: "oxybricks", label: "OxyBricks", key: "queriesOxybricks" },
      { icon: "lender", label: "OxyLoans Lender", key: "queriesLender" },
      { icon: "borrower", label: "OxyLoans Borrower", key: "queriesBorrower" },
    ],
  },
    {
    label: "Campaign Data",
    items: [
{ icon: "dashboard", label: "Dashboard", key: "campaignDashboard" },
      { icon: "database", label: "Rotary Data", key: "rotaryData" },
      { icon: "database", label: "CBS Data", key: "cbsData" },
      { icon: "database", label: "Advocate Data", key: "advocatesData" },
      { icon: "database", label: "FTCCI Data", key: "ftcciData" },
      { icon: "database", label: "Mumbai Data", key: "mumbaiData" },
      { icon: "database", label: "Kukatpally Data", key: "kukatpallyData" },
      { icon: "database", label: "Sudheer Vakkalagadda Data", key: "sudheerVakkalagaddaData" },
      { icon: "database", label: "Thalwar Data", key: "talwarData" },
      { icon: "database", label: "Ram Mohan Darisa Data", key: "ramMohanDarisaData" },
    ],
  },
  {
    label: "System",
    items: [
      { icon: "logout", label: "Logout", key: "logout", danger: true },
    ],
  },
];

/* ── Section config — columns + API endpoint placeholder ─── */
export const SECTIONS = {
  dashboard: {
    title: "Dashboard",
    subtitle: "Overview of all users",
    color: "#2563eb",
    icon: <DashboardOutlined />,
  },
  lender: {
    title: "OxyLoans Lender",
    subtitle: "All registered lender users",
    color: "#2563eb",
    icon: <BankOutlined />,
    endpoint: "/user-service/lenders", // replace with real endpoint
    columns: ["Name", "Email", "Mobile", "Amount", "Status", "Joined"],
    rowKeys: ["name", "email", "mobile", "amount", "status", "createdDate"],
  },
  borrower: {
    title: "OxyLoans Borrower",
    subtitle: "All registered borrower users",
    color: "#7c3aed",
    icon: <WalletOutlined />,
    endpoint: "/user-service/borrowers",
    columns: ["Name", "Email", "Mobile", "Loan Amt", "Status", "Joined"],
    rowKeys: ["name", "email", "mobile", "loanAmount", "status", "createdDate"],
  },
  askoxy: {
    title: "AskOxy.AI",
    subtitle: "Registered users on AskOxy.AI",
    color: "#0891b2",
    icon: <RobotOutlined />,
  },
  oxybricks: {
    title: "OxyBricks",
    subtitle: "OxyBricks property users",
    color: "#b45309",
    icon: <BuildOutlined />,
    endpoint: "/user-service/oxybricks-users",
    columns: ["Name", "Email", "Mobile", "Property", "Status", "Joined"],
    rowKeys: [
      "name",
      "email",
      "mobile",
      "propertyType",
      "status",
      "createdDate",
    ],
  },
  oxygold: {
    title: "OxyGold",
    subtitle: "OxyGold investment users",
    color: "#d97706",
    icon: <TrophyOutlined />,
  },
  partnerlender: {
    title: "Partner",
    subtitle: "Registered partner accounts",
    color: "#059669",
    icon: <TeamOutlined />,
    endpoint: "/user-service/partners",
    columns: ["Name", "Email", "Mobile", "Type", "Status", "Joined"],
    rowKeys: ["name", "email", "mobile", "partnerType", "status", "createdDate"],
  },
  interested: {
    title: "Interested",
    subtitle: "Users who expressed interest",
    color: "#e11d48",
    icon: <StarOutlined />,
  },
  settings: {
    title: "Settings",
    subtitle: "Admin panel settings",
    color: "#475569",
    icon: <SettingOutlined />,
  },
  campaignDashboard: {
    title: "Campaign Data Dashboard",
    subtitle: "Total record counts across every campaign dataset",
    color: "#d97706",
    icon: <DatabaseOutlined />,
  },
  rotaryData: {
    title: "Rotary Data",
    subtitle: "Rotary members and campaign contacts",
    color: "#7c3aed",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/marketing-service/campgin/rotary-data?page=0&size=500`,
    columns: ["Name", "Club", "City", "State", "Mobile", "Email", "Joined"],
    rowKeys: [
      "name",
      "clubName",
      "city", 
      "state",
      "mobileNumbers",
      "emails",
      "createdAt",
    ],
  },
  cbsData: {
    title: "CBS Data",
    subtitle: "CBS student and professional network records",
    color: "#0891b2",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/agent/getAllCbsData?page=0&size=500`,
    columns: ["Name", "Email", "City", "Country", "Mobile", "LinkedIn"],
    rowKeys: ["name", "email", "city", "country", "phoneNumber", "linkedinUrl"],
  },
  advocatesData: {
    title: "Advocate Data",
    subtitle: "Advocates and legal practitioner directory",
    color: "#a78bfa",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/user-service/getAllAdvocatesData?pageNo=1&pageSize=500`,
    columns: ["Name", "Mobile", "Address", "Joined"],
    rowKeys: ["name1", "mobileNumber", "address", "createdAt"],
  },
  ftcciData: {
    title: "FTCCI Data",
    subtitle: "FTCCI business chamber member contacts",
    color: "#2dd4bf",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/agent/FtcciData?page=0&size=100`,
    columns: ["Company", "Email", "Phone", "Address", "Representatives", "Business"],
    rowKeys: ["companyName", "emails", "phones", "address", "representatives", "nb"],
  },
  mumbaiData: {
    title: "Mumbai Data",
    subtitle: "Mumbai campaign contacts",
    color: "#f97316",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/user-service/getAllMumbaiData?pageNo=1&pageSize=500`,
    columns: ["Name", "Mobile", "Address", "Joined"],
    rowKeys: [
      "name",
      "mobileNumber",
      "address",
      "createdAt",
    ],
  },
  kukatpallyData: {
    title: "Kukatpally Data",
    subtitle: "Kukatpally campaign contacts",
    color: "#0ea5e9",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/user-service/AllKukatpallyData?pageNo=1&pageSize=500`,
    columns: ["Name", "Mobile", "House Number", "Joined"],
    rowKeys: [
      "name",
      "mobileNumber",
      "houseNumber",
      "createdAt",
    ],
  },
  sudheerVakkalagaddaData: {
    title: "Sudheer Vakkalagadda Data",
    subtitle: "Contact records",
    color: "#db2777",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/agent/sudheerVakkalagadda?page=0&size=500`,
    columns: ["Name", "Mobile"],
    rowKeys: ["name", "mobileNumber"],
  },
  talwarData: {
    title: "Thalwar Data",
    subtitle: "Thalwar campaign contacts",
    color: "#16a34a",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/user-service/getAllTalwarData?pageNo=1&pageSize=500`,
    columns: ["Name", "Mobile", "Joined"],
    rowKeys: [
      "name",
      "mobileNumber",
      "createdAt",
    ],
  },
  ramMohanDarisaData: {
    title: "Ram Mohan Darisa Data",
    subtitle: "Contact records",
    color: "#4f46e5",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/agent/getAllRamMohanDarisa?page=0&size=500`,
    columns: ["Name", "Mobile"],
    rowKeys: ["name", "mobileNumber"],
  },
  queriesDashboard: {
    title: "Queries Dashboard",
    subtitle: "Overview of all queries",
    color: "#2563eb",
    icon: <DashboardOutlined />,
  },
  queriesAskoxy: {
    title: "AskOxy.AI Queries",
    subtitle: "Queries raised via AskOxy.AI",
    color: "#0891b2",
    icon: <RobotOutlined />,
  },
  queriesOxybricks: {
    title: "OxyBricks Queries",
    subtitle: "Queries raised via OxyBricks",
    color: "#b45309",
    icon: <BuildOutlined />,
  },
  queriesLender: {
    title: "OxyLoans Lender Queries",
    subtitle: "Queries raised by lenders",
    color: "#2563eb",
    icon: <BankOutlined />,
  },
  queriesBorrower: {
    title: "OxyLoans Borrower Queries",
    subtitle: "Queries raised by borrowers",
    color: "#7c3aed",
    icon: <WalletOutlined />,
  },
};
/* ── Dashboard Overview stats ────────────────────────────────
   `value` is a placeholder until these are wired to real counts
   (e.g. per-section record totals from the API).            ── */
export const OVERVIEW_STATS = [
  {
    label: "Total Users",
    key: "totalUsers",
    icon: <TeamOutlined />,
    color: "#2563eb",
  },
  {
    label: "Today",
    key: "todayUsers",
    icon: <CalendarOutlined />,
    color: "#0891b2",
  },
  {
    label: "Yesterday",
    key: "yesterdayUsers",
    icon: <HistoryOutlined />,
    color: "#7c3aed",
  },
  {
    label: "This Week",
    key: "thisWeekUsers",
    icon: <BarChartOutlined />,
    color: "#059669",
  },
  {
    label: "This Month",
    key: "thisMonthUsers",
    icon: <LineChartOutlined />,
    color: "#d97706",
  },
];