import {
  BankOutlined,
  WalletOutlined,
  RobotOutlined,
  BuildOutlined,
  TrophyOutlined,
  TeamOutlined,
  StarOutlined,
  SettingOutlined,
  DashboardOutlined,
  CalendarOutlined,
  HistoryOutlined,
  BarChartOutlined,
  LineChartOutlined,
  DatabaseOutlined,
} from "@ant-design/icons";
import BASE_URL from "../../../core/config/Config";

/* ── Sidebar nav ─────────────────────────────────────────── */
export const NAV_SECTIONS = [
  {
    label: "USERS REGISTRATIONS",
    items: [
      { icon: "dashboard", label: "Dashboard", key: "dashboard" },
      { icon: "lender", label: "OxyLoans Lender", key: "lender" },
      { icon: "borrower", label: "OxyLoans Borrower", key: "borrower" },
      { icon: "askoxy", label: "AskOxy.AI", key: "askoxy" },
      { icon: "oxybricks", label: "OxyBricks", key: "oxybricks" },
      { icon: "oxygold", label: "OxyGold", key: "oxygold" },
      { icon: "partnerlender", label: "Oxyloans Partner", key: "partnerlender" },
      { icon: "interested", label: "Interested", key: "interested" },
      { icon: "journeyScorecard", label: "Interested Scorecard", key: "journeyScorecard" },
    ],
  },
  {
    label: "Queries",
    items: [
      { icon: "dashboard", label: "Dashboard", key: "queriesDashboard" },
      { icon: "askoxy", label: "AskOxy.AI", key: "queriesAskoxy" },
      { icon: "oxybricks", label: "OxyBricks", key: "queriesOxybricks" },
      { icon: "lender", label: "OxyLoans Lender", key: "queriesLender" },
      { icon: "borrower", label: "OxyLoans Borrower", key: "queriesBorrower" },
    ],
  },
    {
    label: "Campaign Data",
    items: [
{ icon: "dashboard", label: "Dashboard", key: "campaignDashboard" },
      { icon: "database", label: "AskOxy Users", key: "askoxyHelpdeskData" },
      { icon: "database", label: "Rotary Data", key: "rotaryData" },
      { icon: "database", label: "CBS Data", key: "cbsData" },
      { icon: "database", label: "Advocate Data", key: "advocatesData" },
      { icon: "database", label: "FTCCI Data", key: "ftcciData" },
      { icon: "database", label: "Mumbai Data", key: "mumbaiData" },
      { icon: "database", label: "Kukatpally Data", key: "kukatpallyData" },
      { icon: "database", label: "Thalwar Data", key: "talwarData" },
      { icon: "database", label: "Ram Mohan Darisa Data", key: "ramMohanDarisaData" },
      { icon: "database", label: "AMFI Data", key: "amfiData" },
      { icon: "database", label: "Radha LinkedIn Data", key: "radhaLinkedinData" },
      { icon: "database", label: "Naukri Data", key: "naukariData" },
      { icon: "database", label: "Sudheer Data", key: "sudheerData" },
      { icon: "database", label: "Tahsildar Data", key: "tahsildarData" },
      { icon: "database", label: "Active Membership", key: "activeMembershipData" },
      { icon: "database", label: "AMS Lost Customer Data", key: "amsLostCustomerData" },
      { icon: "database", label: "Client Wise AUM Report", key: "clientWiseAumData" },
      { icon: "database", label: "K2K Fintech Data", key: "k2kFintechData" },
      { icon: "database", label: "Saksham Data", key: "sakshamData" },
      { icon: "database", label: "TiE Data", key: "tieData" },
      { icon: "database", label: "Two Years Service Data", key: "twoYearsServiceData" },
      { icon: "database", label: "Unknown Data", key: "unknownData" },
      { icon: "database", label: "Naukri RAS", key: "naukriRasData" },
    ],
  },
  {
    label: "System",
    items: [
      { icon: "logout", label: "Logout", key: "logout", danger: true },
    ],
  },
];

/* ── Section config — columns + API endpoint placeholder ─── */
export const SECTIONS = {
  dashboard: {
    title: "Dashboard",
    subtitle: "Overview of all users",
    color: "#2563eb",
    icon: <DashboardOutlined />,
  },
  lender: {
    title: "OxyLoans Lender",
    subtitle: "All registered lender users",
    color: "#2563eb",
    icon: <BankOutlined />,
    endpoint: "/user-service/lenders", // replace with real endpoint
    columns: ["Name", "Email", "Mobile", "Amount", "Status", "Joined"],
    rowKeys: ["name", "email", "mobile", "amount", "status", "createdDate"],
  },
  borrower: {
    title: "OxyLoans Borrower",
    subtitle: "All registered borrower users",
    color: "#7c3aed",
    icon: <WalletOutlined />,
    endpoint: "/user-service/borrowers",
    columns: ["Name", "Email", "Mobile", "Loan Amt", "Status", "Joined"],
    rowKeys: ["name", "email", "mobile", "loanAmount", "status", "createdDate"],
  },
  askoxy: {
    title: "AskOxy.AI",
    subtitle: "Registered users on AskOxy.AI",
    color: "#0891b2",
    icon: <RobotOutlined />,
  },
  oxybricks: {
    title: "OxyBricks",
    subtitle: "OxyBricks property users",
    color: "#b45309",
    icon: <BuildOutlined />,
    endpoint: "/user-service/oxybricks-users",
    columns: ["Name", "Email", "Mobile", "Property", "Status", "Joined"],
    rowKeys: [
      "name",
      "email",
      "mobile",
      "propertyType",
      "status",
      "createdDate",
    ],
  },
  oxygold: {
    title: "OxyGold",
    subtitle: "OxyGold investment users",
    color: "#d97706",
    icon: <TrophyOutlined />,
  },
  partnerlender: {
    title: "Partner",
    subtitle: "Registered partner accounts",
    color: "#059669",
    icon: <TeamOutlined />,
    endpoint: "/user-service/partners",
    columns: ["Name", "Email", "Mobile", "Type", "Status", "Joined"],
    rowKeys: ["name", "email", "mobile", "partnerType", "status", "createdDate"],
  },
  interested: {
    title: "Interested",
    subtitle: "Users who expressed interest",
    color: "#e11d48",
    icon: <StarOutlined />,
  },
  journeyScorecard: {
    title: "Interested Scorecard",
    subtitle: "Today/Yesterday/Week/Month per registration journey",
    color: "#0284c7",
    icon: <TrophyOutlined />,
  },
  settings: {
    title: "Settings",
    subtitle: "Admin panel settings",
    color: "#475569",
    icon: <SettingOutlined />,
  },
  campaignDashboard: {
    title: "Campaign Data Dashboard",
    subtitle: "Total record counts across every campaign dataset",
    color: "#d97706",
    icon: <DatabaseOutlined />,
  },
  askoxyHelpdeskData: {
    title: "AskOxy Users",
    subtitle: "Askoxy registered users assigned to HelpDesk",
    color: "#818cf8",
    icon: <DatabaseOutlined />,
    method: "POST",
    endpoint: `${BASE_URL}/user-service/allOxyUsersAssignedToHelpDesk`,
    body: { pageNo: 1, pageSize: 50 },
    columns: ["Name", "Mobile", "Email", "Joined"],
    rowKeys: ["name", "mobileNumber", "email", "createdAt"],
    dedupeKeys: ["name", "email"],
  },
  rotaryData: {
    title: "Rotary Data",
    subtitle: "Rotary members and campaign contacts",
    color: "#7c3aed",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/marketing-service/campgin/rotary-data?page=0&size=50`,
    columns: ["Name", "Club", "City", "State", "Mobile", "Email", "Joined"],
    rowKeys: [
      "name",
      "clubName",
      "city", 
      "state",
      "mobileNumbers",
      "emails",
      "createdAt",
    ],
  },
  cbsData: {
    title: "CBS Data",
    subtitle: "CBS student and professional network records",
    color: "#0891b2",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/agent/getAllCbsData?page=0&size=50`,
    columns: ["Name", "Email", "City", "Country", "Mobile", "LinkedIn"],
    rowKeys: ["name", "email", "city", "country", "phoneNumber", "linkedinUrl"],
  },
  advocatesData: {
    title: "Advocate Data",
    subtitle: "Advocates and legal practitioner directory",
    color: "#6d28d9",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/user-service/getAllAdvocatesData?pageNo=1&pageSize=50`,
    columns: ["Name", "Mobile", "Address", "Joined"],
    rowKeys: ["name1", "mobileNumber", "address", "createdAt"],
  },
  ftcciData: {
    title: "FTCCI Data",
    subtitle: "FTCCI business chamber member contacts",
    color: "#2dd4bf",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/agent/FtcciData?page=0&size=50`,
    columns: ["Company", "Email", "Phone", "Address", "Representatives", "Business"],
    rowKeys: ["companyName", "emails", "phones", "address", "representatives", "nb"],
  },
  mumbaiData: {
    title: "Mumbai Data",
    subtitle: "Mumbai campaign contacts",
    color: "#f97316",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/user-service/getAllMumbaiData?pageNo=1&pageSize=50`,
    columns: ["Name", "Mobile", "Address", "Joined"],
    rowKeys: [
      "name",
      "mobileNumber",
      "address",
      "createdAt",
    ],
  },
  kukatpallyData: {
    title: "Kukatpally Data",
    subtitle: "Kukatpally campaign contacts",
    color: "#0ea5e9",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/user-service/AllKukatpallyData?pageNo=1&pageSize=50`,
    columns: ["Name", "Mobile", "House Number", "Joined"],
    rowKeys: [
      "name",
      "mobileNumber",
      "houseNumber",
      "createdAt",
    ],
  },
  talwarData: {
    title: "Thalwar Data",
    subtitle: "Thalwar campaign contacts",
    color: "#16a34a",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/user-service/getAllTalwarData?pageNo=1&pageSize=50`,
    columns: ["Name", "Mobile", "Email", "Joined"],
    rowKeys: [
      "name",
      "mobileNumber",
      "email",
      "createdAt",
    ],
  },
  ramMohanDarisaData: {
    title: "Ram Mohan Darisa Data",
    subtitle: "Contact records",
    color: "#4f46e5",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/agent/getAllRamMohanDarisa?page=0&size=50`,
    columns: ["Name", "Mobile"],
    rowKeys: ["name", "mobileNumber"],
  },
  amfiData: {
    title: "AMFI Data",
    subtitle: "AMFI mutual fund holders directory",
    color: "#0d9488",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/amfi-reports?page=0&size=50`,
    columns: ["Name", "Pin", "Email", "City", "Telephone (R)", "Telephone (O)"],
    rowKeys: ["holdersName", "pin", "email", "city", "telephoneR", "telephoneO"],
    // Same holder can appear in multiple scrapes with different fields
    // filled in — identify duplicates by name + pin alone so the merge in
    // dedupeRows can fill in whichever fields each copy has.
    dedupeKeys: ["holdersName", "pin"],
  },
  radhaLinkedinData: {
    title: "Radha LinkedIn Data",
    subtitle: "LinkedIn contact records",
    color: "#0a66c2",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/radha-linkedin?page=0&size=50`,
    columns: ["Name", "Email", "Company", "Job Title"],
    rowKeys: ["name", "emailAddress", "company", "jobTitle"],
    dedupeKeys: ["name", "emailAddress"],
  },
  naukariData: {
    title: "Naukri Records",
    subtitle: "Naukri.com candidate resume records",
    color: "#e2670e",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/sa-naukari-records?page=0&size=50`,
    columns: [
      "Name",
      "Experience",
      "Location",
      "Salary",
      "Current Role",
      "Contact",
      "Email",
      "Key Skills",
      "Preferred Location",
    ],
    rowKeys: [
      "candidateName",
      "workExperience",
      "location",
      "salary",
      "currentDesignationAndCompany",
      "contactNo",
      "emailIds",
      "keySkills",
      "preferredLocation",
    ],
    dedupeKeys: ["candidateName", "contactNo"],
  },
  sudheerData: {
    title: "Sudheer Data",
    subtitle: "Professional contact records",
    color: "#9333ea",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/sudheer-data?page=0&size=50`,
    columns: ["Name", "Title", "Company", "Phone", "Email", "Address"],
    rowKeys: ["name", "title", "company", "phoneNumber", "mailId", "address"],
    dedupeKeys: ["name", "mailId"],
  },
  tahsildarData: {
    title: "Tahsildar Data",
    subtitle: "Tahsildar office contact directory",
    color: "#65a30d",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/tahsildar?page=0&size=50`,
    columns: ["Name", "Designation", "Mobile", "Office Number", "Office Address", "Email"],
    rowKeys: ["name", "designation", "mobileNo", "officeNumber", "officeAddress", "email"],
    dedupeKeys: ["name", "mobileNo"],
  },
  activeMembershipData: {
    title: "Active Membership",
    subtitle: "Active membership member directory",
    color: "#10b981",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/active-membership?page=0&size=50`,
    columns: ["Name", "Mobile", "Email"],
    rowKeys: ["name", "mobileNumber", "email"],
    dedupeKeys: ["name", "email"],
  },
  amsLostCustomerData: {
    title: "AMS Lost Customer Data",
    subtitle: "AMS lost customer contact directory",
    color: "#f97316",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/ams-lost-customer-data?page=0&size=50`,
    columns: ["Name", "Mobile", "Email"],
    rowKeys: ["name", "mobileNumber", "email"],
    dedupeKeys: ["name", "email"],
  },
  clientWiseAumData: {
    title: "Client Wise AUM Report",
    subtitle: "Client-wise assets under management report",
    color: "#4338ca",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/client-wise-aum-report?page=0&size=50`,
    columns: [
      "Client Name",
      "Client Code",
      "Branch Code",
      "Advisor Name",
      "Sub Broker",
      "Product",
      "Total AUM",
    ],
    rowKeys: [
      "clientName",
      "clientCode",
      "branchCode",
      "advisorName",
      "subBrokerCode",
      "product",
      "totalAum",
    ],
    dedupeKeys: ["clientCode", "ucid"],
  },
  k2kFintechData: {
    title: "K2K Fintech Data",
    subtitle: "K2K Fintech contact directory",
    color: "#059669",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/k2k-fintech?page=0&size=50`,
    columns: ["Name", "Mobile", "Email"],
    rowKeys: ["name", "mobileNumber", "email"],
    dedupeKeys: ["name", "email"],
  },
  sakshamData: {
    title: "Saksham Data",
    subtitle: "Saksham directory contacts",
    color: "#0284c7",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/saksham?page=0&size=50`,
    columns: ["Name", "Mobile", "Email"],
    rowKeys: ["name", "mobileNumber", "email"],
    dedupeKeys: ["name", "email"],
  },
  tieData: {
    title: "TiE Data",
    subtitle: "TiE entrepreneurship network members directory",
    color: "#059669",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/tie-data?page=0&size=50`,
    columns: ["Name", "Email"],
    rowKeys: ["name", "email"],
    dedupeKeys: ["name", "email"],
    mergeEmailFields: ["email1", "email2"],
  },
  twoYearsServiceData: {
    title: "Two Years Service Data",
    subtitle: "Two years service customer directory",
    color: "#9333ea",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/two-years-service-data?page=0&size=50`,
    columns: ["Name", "Mobile", "Email"],
    rowKeys: ["name", "mobileNumber", "email"],
    dedupeKeys: ["name", "email"],
  },
  unknownData: {
    title: "Unknown Data",
    subtitle: "Regional contact records with names, mobile numbers, and addresses",
    color: "#64748b",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/unknow-data?page=0&size=50`,
    columns: ["Name", "Mobile", "Address"],
    rowKeys: ["name", "mobileNumber", "address"],
  },
  naukriRasData: {
    title: "Naukri RAS",
    subtitle: "Naukri RAS candidate profiles",
    color: "#2563eb",
    icon: <DatabaseOutlined />,
    endpoint: `${BASE_URL}/ai-service/entity-records/naukri-ras?page=0&size=50`,
    columns: ["Name", "Mobile"],
    rowKeys: ["name", "mobileNumber"],
    dedupeKeys: ["name", "mobileNumber"],
  },
  queriesDashboard: {
    title: "Queries Dashboard",
    subtitle: "Overview of all queries",
    color: "#2563eb",
    icon: <DashboardOutlined />,
  },
  queriesAskoxy: {
    title: "AskOxy.AI Queries",
    subtitle: "Queries raised via AskOxy.AI",
    color: "#0891b2",
    icon: <RobotOutlined />,
  },
  queriesOxybricks: {
    title: "OxyBricks Queries",
    subtitle: "Queries raised via OxyBricks",
    color: "#b45309",
    icon: <BuildOutlined />,
  },
  queriesLender: {
    title: "OxyLoans Lender Queries",
    subtitle: "Queries raised by lenders",
    color: "#2563eb",
    icon: <BankOutlined />,
  },
  queriesBorrower: {
    title: "OxyLoans Borrower Queries",
    subtitle: "Queries raised by borrowers",
    color: "#7c3aed",
    icon: <WalletOutlined />,
  },
};
/* ── Dashboard Overview stats ────────────────────────────────
   `value` is a placeholder until these are wired to real counts
   (e.g. per-section record totals from the API).            ── */
export const OVERVIEW_STATS = [
  {
    label: "Total Users",
    key: "totalUsers",
    icon: <TeamOutlined />,
    color: "#2563eb",
  },
  {
    label: "Today",
    key: "todayUsers",
    icon: <CalendarOutlined />,
    color: "#0891b2",
  },
  {
    label: "Yesterday",
    key: "yesterdayUsers",
    icon: <HistoryOutlined />,
    color: "#7c3aed",
  },
  {
    label: "This Week",
    key: "thisWeekUsers",
    icon: <BarChartOutlined />,
    color: "#059669",
  },
  {
    label: "This Month",
    key: "thisMonthUsers",
    icon: <LineChartOutlined />,
    color: "#d97706",
  },
];